import './globals.css'
import { GTMnoscript } from './lib/GTMnoscript'
import { GAscript } from './lib/GAscript'
import { GTMscript } from './lib/GTMscript'
export const metadata = {
  title: 'TPM DEMO',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
      <GTMscript/>
      <GAscript />
    </head>
      <body>
        {children}
        
        <GTMnoscript />
      </body>
    </html>
  )
}
